# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cmd: Rscript -e "writeLines('options(repos = \'https://cloud.r-project.org\')', '~/.Rprofile')"
  - cmd: Rscript -e "getOption('repos')"
  - cmd: Rscript -e "if (!requireNamespace('remotes', quietly = TRUE)) install.packages('remotes')"
  - cmd: Rscript -e "if (!requireNamespace('curl', quietly = TRUE)) install.packages('curl')"
  - cmd: Rscript -e "if (!requireNamespace('tic', quietly = TRUE)) remotes::install_github('ropenscilabs/tic')"
  - cmd: Rscript -e "tic::prepare_all_stages()"
  - cmd: Rscript -e "tic::before_install()"

cache:
- C:\RLibrary\

before_build: Rscript -e "tic::before_install()"
build_script: Rscript -e "tic::install()"
after_build: Rscript -e "tic::after_install()"
before_test: Rscript -e "tic::before_script()"
test_script: Rscript -e "tic::script()"
on_success: Rscript -e "try(tic::after_success(), silent = TRUE)"
on_failure: Rscript -e "tic::after_failure()"
before_deploy: Rscript -e "tic::before_deploy()"
deploy_script: Rscript -e "tic::deploy()"
after_deploy: Rscript -e "tic::after_deploy()"
on_finish: Rscript -e "tic::after_script()"

# Adapt as necessary starting from here

#on_failure:
#  - 7z a failure.zip *.Rcheck\*
#  - appveyor PushArtifact failure.zip

environment:
  # R_QPDF=true makes sure that R CMD check doesn't complain
  # about a missing qpdf executable
  R_QPDF: "true"
  GITHUB_PAT:
    secure: VXO22OHLkl4YhVIomSMwCZyOTx03Xf2WICaVng9xH7gISlAg8a+qrt1DtFtk8sK5

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
